// Section 5: רפלקציה / סיכום אישי
const H = require('./helpers');
const { push, h, he, code, spacer, pageBreak, image, diagram, infoBox, tbl2col, Paragraph, TextRun, AlignmentType } = H;

push(
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 2400, after: 400 },
    children: [new TextRun({ text: "פרק 5", bold: true, size: 80, font: "Arial", color: "C00000" })] }),
  new Paragraph({ bidirectional: true, alignment: AlignmentType.CENTER, spacing: { after: 400 },
    children: [new TextRun({ text: "רפלקציה / סיכום אישי", bold: true, size: 60, font: "Arial", color: "1F3864", rightToLeft: true })] }),
  pageBreak()
);

push(
  h("5.1 תהליך העבודה על הפרויקט", 1),
  he("פרויקט TRAXONET לוויתי שנה שלמה. במבט לאחור, התהליך היה מאתגר, מספק ולמעלה לכל ציפייה הראשונית שלי. בפרק הזה אני סוקר את התהליך, ההצלחות, האתגרים, והדרכים בהן התמודדתי איתם."),
  spacer(),
  h("ההצלחות העיקריות", 2),
  he("**הצלחה 1: בניית מערכת end-to-end עובדת.** מהרגע הראשון שראיתי לקוח שולח נתונים והם מופיעים ב-Dashboard בדפדפן בזמן אמת — היה רגע של סיפוק עצום. הכל עובד יחד."),
  he("**הצלחה 2: יישום הצפנה מאפס.** ה-handshake של RSA+AES שיישמתי בעצמי, ולא השתמשתי ב-TLS מוכן, נתן לי הבנה עמוקה של איך הצפנה אסימטרית וסימטרית עובדות יחד. זה היה אחד הקטעים שאני הכי גאה בהם."),
  he("**הצלחה 3: למדתי SignalR.** עד שהתחלתי את הפרויקט לא ידעתי בכלל מה זה SignalR. עכשיו אני מבין WebSockets, fallback ל-long polling, ו-Hub patterns."),
  he("**הצלחה 4: עיצוב Dashboard ויזואלי.** השקעתי הרבה ב-CSS — gradient backgrounds, particle animations, gauge charts. התוצאה הסופית נראית מקצועית."),
  he("**הצלחה 5: אגרסטיביות לבעיות BIDI.** הספר בעברית עם קוד אנגלי הציב אתגר רינדור משמעותי. למדתי על BIDI Unicode algorithm, LRM/FSI marks, ו-RTL paragraph properties."),
  spacer(),
  h("האתגרים והקשיים", 2),
  he("**אתגר 1: WMI לא תמיד מחזיר מידע.** במחשב הביתי שלי, MSAcpi_ThermalZoneTemperature לא היה זמין. נאלצתי לחפש את LibreHardwareMonitor כ-fallback. למדתי שלא לסמוך על API אחד בלבד."),
  he("**אתגר 2: סנכרון מפתחות בין שני הפרויקטים.** שני projects צריכים את אותם RSA/AES keys ב-appsettings. שכחתי פעם לעדכן את אחד והגיעו שעות של debugging עד שזיהיתי שהבעיה היא שני קבצי config מנותקים."),
  he("**אתגר 3: BIDI בWord.** הראיתי את הספר למישהו אחר והוא אמר \"זה נראה הפוך\". זה הוביל אותי ללמוד את כל BIDI Unicode standard ולהוסיף marks ייחודיים."),
  he("**אתגר 4: PerformanceCounter דורש 2 קריאות + 1 שנייה.** בהתחלה חשבתי שמשהו לא עובד כי הראשונה תמיד מחזירה 0. למדתי ש-counters הם delta — צריך baseline."),
  he("**אתגר 5: WinForms BIDI עם רכיבים מעורבים.** רציתי שה-LoginForm יראה טוב גם בעברית. נאלצתי לעבוד עם RightToLeft.Yes ו-RightToLeftLayout."),
  spacer(),
  h("דרכי פתרון", 2),
  he("**1. תיעוד.** כתבתי הערות בקוד ב-מקומות בעייתיים. עזר לי לחזור חודש אחרי ולהבין למה משהו עובד."),
  he("**2. Stack Overflow + Microsoft Docs.** רוב הבעיות הטכניות נפתרו ע\"י חיפוש מדוקדק. הקפדתי לקרוא את התשובות ולא רק להעתיק."),
  he("**3. Debug Logging.** הוספתי `_log.Info` בכל מקום בעייתי. SignalR Admin UI שאחד כתבתי הפך לכלי debugging מצוין."),
  he("**4. בדיקות קטנות.** במקום לבנות הכל ולקוות שעובד, פיתחתי בקטעים ובדקתי כל יחידה בנפרד."),
  he("**5. חברים שעוזרים.** התייעצתי עם חברים על נושאים שלא הכרתי. אחד הראה לי איך להגדיר Gmail App Password."),
  pageBreak()
);

push(
  h("5.2 תהליך הלמידה", 1),
  he("הפרויקט הזה נתן לי הזדמנות ללמוד הרבה — חלק תוכן שלמדנו בבית הספר, וחלק תוכן שלמדתי באופן עצמאי כדי להתקדם בפרויקט."),
  spacer(),
  h("תכולות חדשות שלמדתי באופן עצמאי", 2),
  he("**1. ASP.NET Core 8.** ידעתי MVC ברמה בסיסית. בפרויקט למדתי עומק: middleware, dependency injection, Cookie Authentication, Background Services, SignalR, Razor."),
  he("**2. Entity Framework Core.** למדתי על LINQ-to-SQL translation, Value Converters, DbContext lifecycle, EF Migrations vs EnsureCreated."),
  he("**3. WMI ו-PerformanceCounter.** APIs של Windows שלא נחשפים בבית הספר. דרשו לימוד דרך MSDN."),
  he("**4. SignalR.** real-time communication על WebSocket. למדתי על Hubs, Clients, IHubContext, ו-OnConnectedAsync."),
  he("**5. Cryptography APIs ב-.NET.** RSA.Create, Aes.Create, RandomNumberGenerator, HMAC, padding modes."),
  he("**6. BIDI Unicode Algorithm.** למדתי בגלל בעיות רינדור עברית. הבנתי איך BIDI עובד, LRM/RLM/FSI/PDI marks."),
  he("**7. Chart.js.** ספריית גרפים. למדתי איך להפעיל doughnut/bar/gauge charts."),
  he("**8. JavaScript modern features.** fetch API, async/await, template literals."),
  he("**9. MySQL UPSERT (ON DUPLICATE KEY UPDATE).** תחביר ייחודי ל-MySQL."),
  he("**10. Docker concepts.** למרות שלא יישמתי, למדתי על containerization ו-microservices architecture."),
  he("**11. Git workflow.** branches, merges, commit messages, .gitignore."),
  he("**12. docx-js (npm).** ספריית JavaScript ליצירת Word documents — שימשה לבניית ספר הפרויקט הזה."),
  spacer(),
  h("איזה כלים אני לוקח להמשך", 2),
  he("**1. ASP.NET Core** — הבנתי שהוא נמצא בכל מקום בעולם enterprise."),
  he("**2. Design patterns:** Singleton, Observer, MVC, Repository — אני יודע איפה להחיל אותם."),
  he("**3. Async/await thinking** — שינוי תפיסה. עכשיו אני חושב async מההתחלה."),
  he("**4. SQL gymnastics:** UPSERT, JOINs, indexes."),
  he("**5. Encryption basics:** מתי להשתמש בRSA, מתי ב-AES, מתי במשולב."),
  he("**6. Debugging methodology** — לוגים מובנים, breakpoints, watch windows."),
  he("**7. Documentation discipline** — לתעד תוך כדי הכתיבה."),
  pageBreak()
);

push(
  h("5.3 תובנות מהתהליך", 1),
  he("**תובנה 1: דבוקה (cohesion) חשובה מ-decoupling.** ניסיתי לפצל את הקוד לחתיכות קטנות \"לפי הספר\", אבל לפעמים זה הקשה על קריאה. למדתי שגם dependency זה אוקיי כשהיא טבעית."),
  he("**תובנה 2: בדיקות תוך כדי פיתוח חוסכות שעות.** הזמן שהשקעתי בכתיבת בדיקות קטנות במהלך הפיתוח חסך לי לפחות 20 שעות של debugging."),
  he("**תובנה 3: תיעוד הוא חלק מהקוד.** קוד ללא תיעוד מתבזבז. אפילו אם אתה כותב לעצמך — תכתוב לעצמך של מחר."),
  he("**תובנה 4: יש לי הרבה ללמוד.** ככל שהבנתי יותר, ראיתי כמה דברים אני לא יודע. זה נותן ענווה."),
  he("**תובנה 5: AI הוא partner מצוין.** השתמשתי ב-Claude ל-debugging, code review, ולכתיבת התיעוד הזה. AI לא מחליף הבנה — אבל מאיץ אותה משמעותית."),
  spacer(),
  h("עזרה ממומחים, שיתוף מידע, ולמידת עמיתים", 2),
  he("**1. המורה.** קיבלתי הנחיה כללית ומקצועית מהמורה לפיתוח תוכנה."),
  he("**2. תלמידים אחרים בכיתה.** התייעצנו על Stack Overflow, חלקנו tips."),
  he("**3. קהילת Stack Overflow.** עזרה גם כשלא שאלתי — חיפושים נתנו תשובות לבעיות שאחרים פתרו."),
  he("**4. Microsoft Docs.** המקור העיקרי לתיעוד טכני."),
  he("**5. Claude AI.** שאלתי שאלות ספציפיות וקיבלתי תשובות עומק. עזר במיוחד עם BIDI ובעיות עיצוב."),
  spacer(),
  h("בראייה לאחור — מה הייתי עושה אחרת?", 2),
  he("**1. הייתי משלב tests מההתחלה.** עכשיו יש לי 0 unit tests. בייצור זה לא יתקבל."),
  he("**2. הייתי בוחר בTLS במקום handshake משלי.** ההצפנה משלי הייתה learning experience, אבל ביצרון TLS היה הרבה יותר בטוח."),
  he("**3. הייתי משתמש ב-Argon2 לסיסמאות.** HMAC-SHA512 \"עובד\" אבל לא מומלץ למתקפת brute force."),
  he("**4. הייתי מוסיף Logger מובנה (Serilog)** במקום LogService שלי. Serilog נותן יותר features עם פחות קוד."),
  he("**5. הייתי כותב סקריפט שמסנכרן keys.** שכפול ב-appsettings של שני פרויקטים הוא error-prone."),
  spacer(),
  h("עם משאבים נוספים — איך הייתי משפר?", 2),
  he("**1. Cloud deployment** — Azure App Service או AWS. ראיתי tutorials, אבל לא יישמתי."),
  he("**2. Mobile app** ל-iOS/Android שמקבל push notifications."),
  he("**3. Historical data + graphs לאורך זמן** עם InfluxDB."),
  he("**4. Multi-tenancy** לתמיכה בכמה ארגונים נפרדים."),
  he("**5. CI/CD pipeline** עם GitHub Actions."),
  he("**6. Tests מקיפים** — unit, integration, e2e."),
  he("**7. Internationalization** — UI גם באנגלית, רוסית."),
  spacer(),
  h("שאלות חקר", 2),
  he("**1.** איך BIDI Unicode פותר טקסט מעורב? למדתי לעומק."),
  he("**2.** למה AES-CBC עם IV של אפסים? יש פגיעות שצריך להבין."),
  he("**3.** איך SignalR בוחר בין WebSocket ל-long-polling?"),
  he("**4.** מה ההבדל בין `IHostedService` ל-`BackgroundService`?"),
  he("**5.** איך EF Core מתרגם LINQ ל-SQL?"),
  spacer(),
  h("תודות", 2),
  he("**תודה למורה** על ההכוונה והעידוד לאורך השנה."),
  he("**תודה לחברי הכיתה** על השיתוף בידע ובעצות."),
  he("**תודה למשפחה** שתמכה במהלך הלילות שבהם דחפתי קוד."),
  he("**תודה לקהילת Stack Overflow ול-Microsoft** על התיעוד המקצועי."),
  he("**תודה ל-Claude AI** על העזרה הטכנית והעצות."),
  pageBreak()
);
