// יומן החלטות + טבלאות נוספות
const H = require('./helpers');
const { push, h, he, code, spacer, pageBreak, image, diagram, infoBox, tbl2col, Paragraph, TextRun, AlignmentType } = H;

push(
  new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 2400, after: 400 },
    children: [new TextRun({ text: "נספח טכני", bold: true, size: 60, font: "Arial", color: "C00000" })] }),
  new Paragraph({ bidirectional: true, alignment: AlignmentType.CENTER, spacing: { after: 400 },
    children: [new TextRun({ text: "יומן החלטות, השוואות והרחבות", bold: true, size: 44, font: "Arial", color: "1F3864", rightToLeft: true })] }),
  pageBreak()
);

push(
  h("יומן החלטות תכנון", 1),
  he("פרק זה אוסף את ההחלטות הטכניות המשמעותיות שעשיתי במהלך הפרויקט — מה החלטתי, מתי, ולמה."),
  spacer(),
  h("החלטה 1: שלושה פרויקטים נפרדים", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי החלטתי", "תחילת ספטמבר, אחרי שעות של ויכוח עם עצמי"],
    ["מה שקלתי", "פרויקט יחיד שעושה הכל, או פיצול ל-2 (Client + Server)"],
    ["מה בחרתי", "פיצול ל-3 — Client, TCP Server, Web App"],
    ["למה", "שיתוף DB ביניהם, גמישות עתידית, פיצול אחריות ברור"],
    ["מה הפסדתי", "שכפול קוד (PasswordHasher, HardwareData)"],
    ["מה הרווחתי", "ארכיטקטורה נקייה, קל לעדכן כל אחד בנפרד"],
  ]),
  spacer(),
  h("החלטה 2: TCP גולמי במקום HTTP", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "אמצע נובמבר"],
    ["מה שקלתי", "HTTPS + WebSocket, gRPC, או TCP יישומי"],
    ["מה בחרתי", "TCP יישומי עם RSA+AES handshake"],
    ["למה", "רציתי ללמוד הצפנה מאפס, לא להסתמך על TLS"],
    ["מה הפסדתי", "לא חוצה proxies/firewalls כמו HTTP. אין load balancing"],
    ["מה הרווחתי", "הבנה עמוקה של איך הצפנה עובדת"],
  ]),
  spacer(),
  h("החלטה 3: MySQL ולא SQL Server", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "ספטמבר"],
    ["מה שקלתי", "SQL Server, PostgreSQL, MySQL, SQLite"],
    ["מה בחרתי", "MySQL 8.0"],
    ["למה", "חינמי, פתוח, ON DUPLICATE KEY UPDATE נטיב, נפוץ"],
    ["מה הפסדתי", "פחות תכונות מ-SQL Server (אין Always Encrypted)"],
    ["מה הרווחתי", "אפס עלות, התקנה פשוטה"],
  ]),
  spacer(),
  h("החלטה 4: שני providers ל-DB", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "דצמבר"],
    ["מה שקלתי", "EF Core בשני הפרויקטים, או MySql.Data בשניהם"],
    ["מה בחרתי", "EF Core ב-Web App, MySql.Data ב-TCP Server"],
    ["למה", "ב-Web App רציתי LINQ. ב-TCP Server רציתי שאילתות raw מהירות"],
    ["מה הפסדתי", "אין אחידות"],
    ["מה הרווחתי", "כל פרויקט קיבל את הכלי הנכון לו"],
  ]),
  spacer(),
  h("החלטה 5: HMAC-SHA512 ולא Argon2", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "דצמבר"],
    ["מה שקלתי", "HMAC-SHA512, PBKDF2, bcrypt, Argon2"],
    ["מה בחרתי", "HMAC-SHA512 + salt אקראי 128 בייט"],
    ["למה", "פשוט יותר, מובנה ב-.NET"],
    ["חיסרון מודע", "מהיר מדי — חשוף ל-brute force"],
    ["תכנון עתידי", "מעבר ל-Argon2 בגרסה הבאה"],
  ]),
  spacer(),
  h("החלטה 6: IV של אפסים להצפנת DB", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "פברואר"],
    ["מה שקלתי", "IV אקראי לכל שדה, או IV דטרמיניסטי"],
    ["מה בחרתי", "IV של אפסים (16 בייט בכולם)"],
    ["למה", "מאפשר WHERE על שדות מוצפנים"],
    ["חיסרון", "ניתוח תדירות אפשרי"],
    ["הצדקה", "use case של ניטור פנימי, נוחות > אבטחה מקסימלית"],
  ]),
  spacer(),
  h("החלטה 7: SignalR ל-Admin UI", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "ינואר"],
    ["מה שקלתי", "long-polling, server-sent events, SignalR"],
    ["מה בחרתי", "SignalR"],
    ["למה", "מובנה ב-ASP.NET Core, fallback אוטומטי, פשוט"],
    ["חיסרון", "scaling דורש Redis backplane (לא רלוונטי כאן)"],
  ]),
  spacer(),
  h("החלטה 8: Polling ב-Dashboard, לא SignalR", 2),
  tbl2col("היבט", "הסבר", [
    ["מתי", "מרץ"],
    ["מה שקלתי", "SignalR ל-Dashboard גם כן"],
    ["מה בחרתי", "setInterval(fetch, 5000)"],
    ["למה", "Dashboard לא קריטי-real-time. Polling פשוט יותר"],
    ["מה הפסדתי", "עיכוב קטן בעדכון"],
    ["מה הרווחתי", "אין החזקת חיבור פתוח לכל משתמש"],
  ]),
  pageBreak()
);

push(
  h("השוואת אפשרויות שהיו", 1),
  he("פרק זה משווה אפשרויות שעמדו על השולחן בנקודות החלטה מרכזיות."),
  spacer(),
  h("הצפנה: השוואת אלטרנטיבות", 2),
  tbl2col("שיטה", "ניקוד שלי (1-10)", [
    ["TLS/HTTPS לתקשורת", "9 — תקני, אבטחה מלאה. נדחה כי רציתי ללמוד"],
    ["RSA + AES hybrid (נבחר)", "7 — לימודי, עובד, נהנה"],
    ["AES בלבד עם static key", "2 — חסר חילוף מפתחות"],
    ["RSA בלבד", "3 — איטי מאוד, גודל הודעה מוגבל"],
    ["IPsec ברמת רשת", "5 — מורכב להגדיר, לא לימודי"],
  ]),
  spacer(),
  h("UI לקוח: השוואת framework-ים", 2),
  tbl2col("Framework", "ניקוד", [
    ["WinForms (נבחר)", "8 — מוכר, מהיר לפיתוח, native"],
    ["WPF", "7 — מודרני יותר אבל XAML מסובך"],
    ["WinUI 3", "5 — חדש, תיעוד מועט"],
    ["MAUI (cross-platform)", "6 — מעניין אבל לא בוגר"],
    ["Avalonia", "5 — קוד פתוח, אבל פחות בוגר"],
    ["Electron + Node", "4 — overkill לאפליקציה קטנה"],
  ]),
  spacer(),
  h("Web framework: השוואה", 2),
  tbl2col("Framework", "ניקוד", [
    ["ASP.NET Core MVC (נבחר)", "9 — מוכר, אינטגרציה עם EF"],
    ["ASP.NET Core Web API + React", "7 — separation אבל overkill"],
    ["Blazor Server", "8 — מעניין, לא מוכר מספיק"],
    ["Node.js + Express", "5 — שינוי שפה, לא היה רוצה"],
    ["Django (Python)", "4 — שפה אחרת"],
    ["Pure HTML/JS + serverless", "3 — לא היה משרת לוגיקה"],
  ]),
  spacer(),
  h("DB: השוואה", 2),
  tbl2col("DB", "ניקוד", [
    ["MySQL 8 (נבחר)", "9 — חינמי, פתוח, UPSERT נטיב"],
    ["PostgreSQL", "8 — חזק יותר אבל UPSERT verbose"],
    ["SQL Server", "8 — חזק, אבל licensing"],
    ["SQLite", "5 — לא מתאים ל-2 כותבים במקביל"],
    ["MongoDB", "4 — schema-less, לא מתאים לקשרים"],
    ["Cassandra", "3 — overkill לכמות שלי"],
  ]),
  pageBreak()
);

push(
  h("טבלת תכונות וסטטוסים", 1),
  he("רשימת תכונות שתכננתי וסטטוס מימוש:"),
  spacer(),
  tbl2col("תכונה", "סטטוס", [
    ["איסוף נתוני CPU/RAM/GPU", "✓ מומש מלא"],
    ["איסוף טמפרטורה", "✓ עם fallback ל--1 אם לא זמין"],
    ["איסוף כוננים", "✓ מומש מלא"],
    ["איסוף IP/MAC", "✓ מומש מלא"],
    ["חיבור TCP מוצפן", "✓ RSA+AES handshake"],
    ["UPSERT ב-DB", "✓ ON DUPLICATE KEY UPDATE"],
    ["הצפנת שדות ב-DB", "✓ 7 שדות עם AES"],
    ["Dashboard web", "✓ עם 3 גרפים, sidebar, settings"],
    ["Auto-refresh כל 5s", "✓ setInterval"],
    ["הגדרת ספים", "✓ 4 סוגי ספים"],
    ["התראות SMTP", "✓ Gmail STARTTLS"],
    ["Cooldown 5 דקות", "✓ static Dictionary"],
    ["שינוי interval דינמי", "✓ דרך GetSettingsAsync"],
    ["Admin UI עם SignalR", "✓ לוגים בזמן אמת"],
    ["ניהול 3 דרכי authorization", "✓ email/permission/owner"],
    ["Owner Lock", "✓ Registry"],
    ["Reset password", "✓ דרך Admin UI"],
    ["Cascade delete של מחשב", "✓ 5 טבלאות"],
    ["Cookie auth", "✓ עם SlidingExpiration"],
    ["Unit tests", "✗ לא מומש"],
    ["Integration tests", "✗ לא מומש"],
    ["Historical data (timeseries)", "✗ לא מומש"],
    ["Mobile app", "✗ לא מומש"],
    ["Docker", "✗ לא מומש"],
    ["CI/CD pipeline", "✗ לא מומש"],
  ]),
  pageBreak()
);

push(
  h("טבלת השוואת ביצועים", 1),
  he("מדידות שעשיתי על מחשב שלי (Intel i7-12700K, 32GB RAM, Windows 11):"),
  spacer(),
  tbl2col("פעולה", "זמן ממוצע", [
    ["WMI Win32_Processor", "כ-50-80 ms"],
    ["WMI Win32_PhysicalMemory", "כ-30-60 ms"],
    ["WMI Win32_LogicalDisk", "כ-100-150 ms"],
    ["WMI Win32_VideoController", "כ-40-70 ms"],
    ["WMI Win32_NetworkAdapter", "כ-200-300 ms (הכי איטי)"],
    ["LibreHardwareMonitor (motherboard)", "כ-80-120 ms"],
    ["PerformanceCounter (CPU)", "כ-1000 ms (delay מובנה)"],
    ["DataCollector.CollectAsync (כולל)", "כ-1.5-2 שניות"],
    ["RSA Encrypt (48 בייט)", "כ-1-3 ms"],
    ["AES Encrypt (3KB)", "כ-0.1 ms"],
    ["TCP connect (localhost)", "כ-1-3 ms"],
    ["TCP connect (LAN)", "כ-50-100 ms"],
    ["UPSERT computer ב-MySQL", "כ-10-15 ms"],
    ["UPSERT drive (אחד)", "כ-5-10 ms"],
    ["EF Core SELECT * ב-Dashboard", "כ-20-50 ms"],
    ["SMTP send (Gmail)", "כ-1-2 שניות"],
    ["Dashboard fetch + render", "כ-100-200 ms"],
  ]),
  spacer(),
  he("**מסקנה:** הצוואר העיקרי הוא PerformanceCounter (1 שנייה קבוע). שאר הפעולות בסך הכל מהירות."),
  pageBreak()
);

push(
  h("שאלות תיאורטיות שעניינו אותי", 1),
  he("במהלך הפיתוח עלו שאלות שלא הכרחי לפרויקט אבל למדתי מהן."),
  spacer(),
  h("שאלה 1: למה IV של אפסים זה לא בטוח?", 2),
  he("**תשובה:** כי כל הצפנה של אותו plaintext נותנת אותו ciphertext. תוקף יכול לעשות ניתוח תדירות — לדוגמה, לראות שערך X מופיע ב-50% מהמחשבים, ולהבין שזה משהו נפוץ (כמו \"WORKGROUP\")."),
  spacer(),
  h("שאלה 2: למה HMAC ולא רק SHA512?", 2),
  he("**תשובה:** HMAC עוטף את ה-hash במנגנון שמשלב מפתח. SHA512 בלבד פגיע ל-length extension attacks. HMAC מתוכנן להיות עמיד."),
  spacer(),
  h("שאלה 3: מה זה network byte order?", 2),
  he("**תשובה:** big-endian. ה-MSB מגיע ראשון. נקבע ב-RFC 1700 כסטנדרט לפרוטוקולים. הסיבה: בזמן ש-x86 הוא little-endian, רוב מערכות ה-mainframe ההיסטוריות היו big-endian."),
  spacer(),
  h("שאלה 4: למה SignalR בוחר בין WebSocket ל-long polling?", 2),
  he("**תשובה:** WebSocket דורש תמיכת דפדפן ו-proxy. אם לא זמין, SignalR נופל ל-long polling (שזה HTTP request שהשרת מחזיק 30 שניות עד שיש מידע). פחות יעיל אבל יותר תואם."),
  spacer(),
  h("שאלה 5: למה Async/Await ולא threading ידני?", 2),
  he("**תשובה:** async/await משחרר את ה-thread ל-thread pool בזמן ה-I/O. Threading ידני יחזיק את ה-thread באוויר. עם 1000 חיבורים מקבילים, async משמש ~10 threads, threading משמש 1000."),
  spacer(),
  h("שאלה 6: מה ההבדל בין IHostedService ל-BackgroundService?", 2),
  he("**תשובה:** `IHostedService` הוא interface בסיסי. `BackgroundService` הוא abstract class שיורש ממנו ומספק תבנית סטנדרטית עם `ExecuteAsync` ו-`CancellationToken`. למימוש פשוט — BackgroundService."),
  pageBreak()
);

push(
  h("טבלת מקבילות בין שפות תכנות", 1),
  he("הפרויקט ב-C#. הכרתי גם Python ו-JavaScript מעט. למדתי איך אותם concepts נראים בכל אחד."),
  spacer(),
  tbl2col("מושג", "ביטוי בכל שפה", [
    ["async function", "C#: async Task<T>; JS: async function; Python: async def"],
    ["await expression", "C#: await; JS: await; Python: await"],
    ["null", "C#: null; JS: null/undefined; Python: None"],
    ["array", "C#: T[] or List<T>; JS: Array; Python: list"],
    ["dict", "C#: Dictionary<K,V>; JS: Map or object; Python: dict"],
    ["lambda", "C#: x => x*2; JS: x => x*2; Python: lambda x: x*2"],
    ["class", "C#: class X; JS: class X; Python: class X"],
    ["interface", "C#: interface IX; JS: לא קיים נטיב; Python: ABC"],
    ["string format", "C#: $\"{x}\"; JS: `${x}`; Python: f\"{x}\""],
    ["exception", "C#: try/catch; JS: try/catch; Python: try/except"],
  ]),
  spacer(),
  h("טבלת מקורות שעזרו לי במיוחד", 2),
  tbl2col("מקור", "מה למדתי", [
    ["IAmTimCorey (YouTube)", "ASP.NET Core MVC, SignalR, Dependency Injection"],
    ["Microsoft Docs", "כל ה-APIs של .NET"],
    ["Stack Overflow", "פתרון לבאגים ספציפיים"],
    ["GitHub (LibreHardwareMonitor)", "WMI alternative"],
    ["Kevin Powell (YouTube)", "CSS animations, layout"],
    ["Pomelo GitHub", "EF Core MySQL provider"],
    ["MDN Web Docs", "JavaScript modern features"],
    ["Stripe Engineering Blog", "REST API design"],
    ["Anthropic (Claude)", "code review, debugging help"],
    ["RFC 8017 (RSA OAEP)", "encryption specifics"],
    ["FIPS 197 (AES)", "encryption specifics"],
    ["Unicode Standard Annex 9 (BIDI)", "Hebrew text rendering"],
  ]),
  pageBreak()
);
